scene.setScale(1.0)
scene.setMediaPath('../../../../data')
scene.addAssetPath('script','sbm-common/scripts')
scene.addAssetPath('mesh', 'mesh')

scene.getSimulationManager().setSimFps(60)

scene.run("zebra2-map.py")
zebra2Map = scene.getJointMapManager().getJointMap("zebra2")

scene.addAssetPath('motion','ChrBrad')
scene.loadAssets()

bradSkeleton = scene.getSkeleton("ChrBrad.sk")
zebra2Map.applySkeleton(bradSkeleton)
zebra2Map.applyMotionRecurse("ChrBrad")

# Brad's face definition
bradFace = scene.createFaceDefinition('ChrBrad')
bradFace.setFaceNeutral('ChrBrad@face_neutral')

bradFace.setAU(1,  "left",  "ChrBrad@001_inner_brow_raiser_lf")
bradFace.setAU(1,  "right", "ChrBrad@001_inner_brow_raiser_rt")
bradFace.setAU(2,  "left",  "ChrBrad@002_outer_brow_raiser_lf")
bradFace.setAU(2,  "right", "ChrBrad@002_outer_brow_raiser_rt")
bradFace.setAU(4,  "left",  "ChrBrad@004_brow_lowerer_lf")
bradFace.setAU(4,  "right", "ChrBrad@004_brow_lowerer_rt")
bradFace.setAU(5,  "both",  "ChrBrad@005_upper_lid_raiser")
bradFace.setAU(6,  "both",  "ChrBrad@006_cheek_raiser")
bradFace.setAU(7,  "both",  "ChrBrad@007_lid_tightener")
bradFace.setAU(10, "both",  "ChrBrad@010_upper_lip_raiser")
bradFace.setAU(12, "left",  "ChrBrad@012_lip_corner_puller_lf")
bradFace.setAU(12, "right", "ChrBrad@012_lip_corner_puller_rt")
bradFace.setAU(25, "both",  "ChrBrad@025_lips_part")
bradFace.setAU(26, "both",  "ChrBrad@026_jaw_drop")
bradFace.setAU(45, "left",  "ChrBrad@045_blink_lf")
bradFace.setAU(45, "right", "ChrBrad@045_blink_rt")

bradFace.setViseme("open",    "ChrBrad@open")
bradFace.setViseme("W",       "ChrBrad@W")
bradFace.setViseme("ShCh",    "ChrBrad@ShCh")
bradFace.setViseme("PBM",     "ChrBrad@PBM")
bradFace.setViseme("FV",      "ChrBrad@FV")
bradFace.setViseme("wide",    "ChrBrad@wide")
bradFace.setViseme("tBack",   "ChrBrad@tBack")
bradFace.setViseme("tRoof",   "ChrBrad@tRoof")
bradFace.setViseme("tTeeth",  "ChrBrad@tTeeth")

brad = scene.createCharacter('ChrBrad', 'ChrBrad')
bradSkeleton = scene.createSkeleton('ChrBrad.sk')
brad.setSkeleton(bradSkeleton)
brad.setFaceDefinition(bradFace)
brad.createStandardControllers()
brad.setDoubleAttribute('deformableMeshScale', .01)
brad.setStringAttribute('deformableMesh', 'ChrBrad')

scene.command("char ChrBrad viewer deformableGPU")

# Setting camera parameters
scene.run('default-viewer.py')
camera = getCamera()
camera.setEye(.08, 1.61, .44)
camera.setCenter(.08, 1.51, -.14)
camera.setUpVector(SrVec(0, 1, 0))
camera.setScale(1)
camera.setFov(1.0472)
camera.setFarPlane(100)
camera.setNearPlane(0.1)
camera.setAspectRatio(0.966897)

scene.getPawn('camera').setPosition(SrVec(0, 1.66, 1.85))

sim.start()
bml.execBML('ChrBrad', '<body posture="ChrBrad@Idle01"/>')

bml.execBMLAt(2, 'ChrBrad', '<face type="FACS" au="1" side="both" amount="1"/>')
scene.commandAt(2.3, 'snapshot')
bml.execBMLAt(3, 'ChrBrad', '<face type="FACS" au="1" side="left" amount="1"/>')
scene.commandAt(3.3, 'snapshot')
bml.execBMLAt(4, 'ChrBrad', '<face type="FACS" au="1" side="right" amount="1"/>')
scene.commandAt(4.3, 'snapshot')

bml.execBMLAt(5, 'ChrBrad', '<face type="FACS" au="2" side="both" amount="1"/>')
scene.commandAt(5.3, 'snapshot')
bml.execBMLAt(6, 'ChrBrad', '<face type="FACS" au="2" side="left" amount="1"/>')
scene.commandAt(6.3, 'snapshot')
bml.execBMLAt(7, 'ChrBrad', '<face type="FACS" au="2" side="right" amount="1"/>')
scene.commandAt(7.3, 'snapshot')

bml.execBMLAt(8, 'ChrBrad', '<face type="FACS" au="4" side="both" amount="1"/>')
scene.commandAt(8.3, 'snapshot')
bml.execBMLAt(9, 'ChrBrad', '<face type="FACS" au="4" side="left" amount="1"/>')
scene.commandAt(9.3, 'snapshot')
bml.execBMLAt(10, 'ChrBrad', '<face type="FACS" au="4" side="right" amount="1"/>')
scene.commandAt(10.3, 'snapshot')

bml.execBMLAt(11, 'ChrBrad', '<face type="FACS" au="5" side="both" amount="1"/>')
scene.commandAt(11.3, 'snapshot')
bml.execBMLAt(12, 'ChrBrad', '<face type="FACS" au="6" side="both" amount="1"/>')
scene.commandAt(12.3, 'snapshot')
bml.execBMLAt(13, 'ChrBrad', '<face type="FACS" au="7" side="both" amount="1"/>')
scene.commandAt(13.3, 'snapshot')
bml.execBMLAt(14, 'ChrBrad', '<face type="FACS" au="10" side="both" amount="1"/>')
scene.commandAt(14.3, 'snapshot')

bml.execBMLAt(15, 'ChrBrad', '<face type="FACS" au="12" side="both" amount="1"/>')
scene.commandAt(15.3, 'snapshot')
bml.execBMLAt(16, 'ChrBrad', '<face type="FACS" au="12" side="left" amount="1"/>')
scene.commandAt(16.3, 'snapshot')
bml.execBMLAt(17, 'ChrBrad', '<face type="FACS" au="12" side="right" amount="1"/>')
scene.commandAt(17.3, 'snapshot')

bml.execBMLAt(18, 'ChrBrad', '<face type="FACS" au="25" side="both" amount="1"/>')
scene.commandAt(18.3, 'snapshot')
bml.execBMLAt(19, 'ChrBrad', '<face type="FACS" au="26" side="both" amount="1"/>')
scene.commandAt(19.3, 'snapshot')

bml.execBMLAt(20, 'ChrBrad', '<face type="FACS" au="45" side="both" amount="1"/>')
scene.commandAt(20.3, 'snapshot')
bml.execBMLAt(21, 'ChrBrad', '<face type="FACS" au="45" side="left" amount="1"/>')
scene.commandAt(21.3, 'snapshot')
bml.execBMLAt(22, 'ChrBrad', '<face type="FACS" au="45" side="right" amount="1"/>')
scene.commandAt(22.3, 'snapshot')

scene.commandAt(23, 'quit')