# state ChrMarineStartingLeft
# autogenerated by SmartBody
def mocapStartLeftSetup(origSkelName,skeletonName, baseJoint, preFix, statePreFix):
	stateManager = scene.getStateManager()

	stateChrMarineStartingLeft = stateManager.createState1D(statePreFix+"StartingLeft")
	stateChrMarineStartingLeft.setBlendSkeleton(origSkelName)
	originalMotions = StringVec()
	originalMotions.append("ChrMarine@Idle01")
	originalMotions.append("ChrMarine@Idle01_ToWalk01_Turn90Lf01")
	originalMotions.append("ChrMarine@Idle01_ToWalk01_Turn180Lf01")
	
	motions = StringVec()
	assetManager = scene.getAssetManager()
	for i in range(0, len(originalMotions)):
		motions.append(preFix + originalMotions[i])
		sbMotion = assetManager.getMotion(originalMotions[i])
		if sbMotion != None:
			sbMotion.setMotionSkeletonName(origSkelName)

	paramsX = DoubleVec()
	paramsX.append(0) # ChrMarine@Idle01 X
	paramsX.append(-90) # ChrMarine@Idle01_ToWalk01_Turn90Lf01 X
	paramsX.append(-180) # ChrMarine@Idle01_ToWalk01_Turn180Lf01 X
	for i in range(0, len(motions)):
		stateChrMarineStartingLeft.addMotion(motions[i], paramsX[i])

	points0 = DoubleVec()
	points0.append(0) # ChrMarine@Idle01 0
	points0.append(0) # ChrMarine@Idle01_ToWalk01_Turn90Lf01 0
	points0.append(0) # ChrMarine@Idle01_ToWalk01_Turn180Lf01 0
	stateChrMarineStartingLeft.addCorrespondencePoints(motions, points0)
	points1 = DoubleVec()
	points1.append(1.36315) # ChrMarine@Idle01 1
	points1.append(1.53) # ChrMarine@Idle01_ToWalk01_Turn90Lf01 1
	points1.append(1.5) # ChrMarine@Idle01_ToWalk01_Turn180Lf01 1
	stateChrMarineStartingLeft.addCorrespondencePoints(motions, points1)
	points2 = DoubleVec()
	points2.append(2.165) # ChrMarine@Idle01 2
	points2.append(2.43) # ChrMarine@Idle01_ToWalk01_Turn90Lf01 2
	points2.append(2.191) # ChrMarine@Idle01_ToWalk01_Turn180Lf01 2
	stateChrMarineStartingLeft.addCorrespondencePoints(motions, points2)	
	
