# state ChrMarineStep
# autogenerated by SmartBody
def mocapStepSetup(origSkelName,skeletonName, baseJoint, preFix, statePreFix):
	stateManager = scene.getStateManager()

	stateChrMarineStep = stateManager.createState2D(statePreFix+"Step")
	stateChrMarineStep.setBlendSkeleton(origSkelName)
	originalMotions = StringVec()
	originalMotions.append("ChrMarine@Idle01")
	originalMotions.append("ChrMarine@Idle01_StepBackwardsLf01")
	originalMotions.append("ChrMarine@Idle01_StepBackwardsRt01")
	originalMotions.append("ChrMarine@Idle01_StepForwardLf01")
	originalMotions.append("ChrMarine@Idle01_StepForwardRt01")
	originalMotions.append("ChrMarine@Idle01_StepSidewaysLf01")
	originalMotions.append("ChrMarine@Idle01_StepSidewaysRt01")
	
	motions = StringVec()
	assetManager = scene.getAssetManager()
	for i in range(0, len(originalMotions)):
		motions.append(preFix + originalMotions[i])
		sbMotion = assetManager.getMotion(originalMotions[i])
		if sbMotion != None:
			sbMotion.setMotionSkeletonName(origSkelName)

	paramsX = DoubleVec()
	paramsY = DoubleVec()
	paramsX.append(8.31458e-005) # ChrMarine@Idle01 X
	paramsY.append(-6.8546e-005) # ChrMarine@Idle01 Y
	paramsX.append(0.0) # ChrMarine@Idle01_StepBackwardsLf01 X
	paramsY.append(-0.349858) # ChrMarine@Idle01_StepBackwardsLf01 Y
	paramsX.append(0.0) # ChrMarine@Idle01_StepBackwardsRt01 X
	paramsY.append(-0.349858) # ChrMarine@Idle01_StepBackwardsRt01 Y
	paramsX.append(-0.0225843) # ChrMarine@Idle01_StepForwardLf01 X
	paramsY.append(0.535643) # ChrMarine@Idle01_StepForwardLf01 Y
	paramsX.append(0.0234374) # ChrMarine@Idle01_StepForwardRt01 X
	paramsY.append(0.535643) # ChrMarine@Idle01_StepForwardRt01 Y
	paramsX.append(-0.234709) # ChrMarine@Idle01_StepSidewaysLf01 X
	paramsY.append(-0.010002) # ChrMarine@Idle01_StepSidewaysLf01 Y
	paramsX.append(0.234693) # ChrMarine@Idle01_StepSidewaysRt01 X
	paramsY.append(-0.010002) # ChrMarine@Idle01_StepSidewaysRt01 Y
	for i in range(0, len(motions)):
		stateChrMarineStep.addMotion(motions[i], paramsX[i], paramsY[i])

	points0 = DoubleVec()
	points0.append(0) # ChrMarine@Idle01 0
	points0.append(0) # ChrMarine@Idle01_StepBackwardsLf01 0
	points0.append(0) # ChrMarine@Idle01_StepBackwardsRt01 0
	points0.append(0) # ChrMarine@Idle01_StepForwardLf01 0
	points0.append(0) # ChrMarine@Idle01_StepForwardRt01 0
	points0.append(0) # ChrMarine@Idle01_StepSidewaysLf01 0
	points0.append(0) # ChrMarine@Idle01_StepSidewaysRt01 0
	stateChrMarineStep.addCorrespondencePoints(motions, points0)
	points1 = DoubleVec()
	points1.append(1.1153) # ChrMarine@Idle01 1
	points1.append(0.68) # ChrMarine@Idle01_StepBackwardsLf01 1
	points1.append(0.68) # ChrMarine@Idle01_StepBackwardsRt01 1
	points1.append(1.02258) # ChrMarine@Idle01_StepForwardLf01 1
	points1.append(1.0303) # ChrMarine@Idle01_StepForwardRt01 1
	points1.append(0.821667) # ChrMarine@Idle01_StepSidewaysLf01 1
	points1.append(0.824242) # ChrMarine@Idle01_StepSidewaysRt01 1
	stateChrMarineStep.addCorrespondencePoints(motions, points1)
	points2 = DoubleVec()
	points2.append(2.165) # ChrMarine@Idle01 2
	points2.append(1.32) # ChrMarine@Idle01_StepBackwardsLf01 2
	points2.append(1.32) # ChrMarine@Idle01_StepBackwardsRt01 2
	points2.append(1.985) # ChrMarine@Idle01_StepForwardLf01 2
	points2.append(2) # ChrMarine@Idle01_StepForwardRt01 2
	points2.append(1.595) # ChrMarine@Idle01_StepSidewaysLf01 2
	points2.append(1.6) # ChrMarine@Idle01_StepSidewaysRt01 2
	stateChrMarineStep.addCorrespondencePoints(motions, points2)

	stateChrMarineStep.addTriangle(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Idle01_StepBackwardsLf01", preFix+"ChrMarine@Idle01_StepSidewaysLf01")
	stateChrMarineStep.addTriangle(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Idle01_StepForwardLf01", preFix+"ChrMarine@Idle01_StepSidewaysLf01")
	stateChrMarineStep.addTriangle(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Idle01_StepBackwardsRt01", preFix+"ChrMarine@Idle01_StepSidewaysRt01")
	stateChrMarineStep.addTriangle(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Idle01_StepForwardRt01", preFix+"ChrMarine@Idle01_StepSidewaysRt01")
