# state marineLocomotion
# autogenerated by SmartBody
def marineLocomotionSetup(origSkelName, skeletonName, baseJoint, preFix, statePreFix):
	stateManager = scene.getStateManager()

	statemarineLocomotion = stateManager.createState3D(statePreFix+"Locomotion")	
	statemarineLocomotion.setBlendSkeleton(origSkelName)
	originalMotions = StringVec()
	originalMotions.append("ChrMarine@Idle01")
	originalMotions.append("ChrMarine@Jog01")
	originalMotions.append("ChrMarine@Meander01")
	originalMotions.append("ChrMarine@Run01")
	originalMotions.append("ChrMarine@RunCircleLf01_smooth")
	originalMotions.append("ChrMarine@RunCircleRt01_smooth")
	originalMotions.append("ChrMarine@RunTightCircleLf01")
	originalMotions.append("ChrMarine@RunTightCircleRt01")
	originalMotions.append("ChrMarine@StrafeSlowLf01")
	originalMotions.append("ChrMarine@StrafeSlowRt01")
	originalMotions.append("ChrMarine@Walk01")
	originalMotions.append("ChrMarine@WalkCircleLf01_smooth")
	originalMotions.append("ChrMarine@WalkCircleRt01_smooth")
	originalMotions.append("ChrMarine@WalkTightCircleLf01_smooth")
	originalMotions.append("ChrMarine@WalkTightCircleRt01_smooth")
	originalMotions.append("ChrMarine@Turn360Lf01")
	originalMotions.append("ChrMarine@Turn360Rt01")
	originalMotions.append("ChrMarine@StrafeFastLf01_smooth")
	originalMotions.append("ChrMarine@StrafeFastRt01_smooth")
	
	motions = StringVec()
	assetManager = scene.getAssetManager()
	for i in range(0, len(originalMotions)):
		motions.append(preFix + originalMotions[i])
		sbMotion = assetManager.getMotion(originalMotions[i])
		if sbMotion != None:
			sbMotion.setMotionSkeletonName(origSkelName)
	# motions.append(preFix+"ChrMarine@Idle01")
	# motions.append(preFix+"ChrMarine@Jog01")
	# motions.append(preFix+"ChrMarine@Meander01")
	# motions.append(preFix+"ChrMarine@Run01")	
	# motions.append(preFix+"ChrMarine@RunCircleLf01_smooth")
	# motions.append(preFix+"ChrMarine@RunCircleRt01_smooth")
	# motions.append(preFix+"ChrMarine@RunTightCircleLf01")
	# motions.append(preFix+"ChrMarine@RunTightCircleRt01")
	# motions.append(preFix+"ChrMarine@StrafeSlowLf01")
	# motions.append(preFix+"ChrMarine@StrafeSlowRt01")
	# motions.append(preFix+"ChrMarine@Walk01")	
	# motions.append(preFix+"ChrMarine@WalkCircleLf01_smooth")
	# motions.append(preFix+"ChrMarine@WalkCircleRt01_smooth")
	# motions.append(preFix+"ChrMarine@WalkTightCircleLf01_smooth")
	# motions.append(preFix+"ChrMarine@WalkTightCircleRt01_smooth")
	# motions.append(preFix+"ChrMarine@Turn360Lf01")
	# motions.append(preFix+"ChrMarine@Turn360Rt01")
	# motions.append(preFix+"ChrMarine@StrafeFastLf01_smooth")
	# motions.append(preFix+"ChrMarine@StrafeFastRt01_smooth")	

	paramsX = DoubleVec()
	paramsY = DoubleVec()
	paramsZ = DoubleVec()
	paramsX.append(0) # ChrMarine@Idle01 X
	paramsY.append(0) # ChrMarine@Idle01 Y
	paramsZ.append(0) # ChrMarine@Idle01 Z
	paramsX.append(0) # ChrMarine@Jog01 X
	paramsY.append(0) # ChrMarine@Jog01 Y
	paramsZ.append(0) # ChrMarine@Jog01 Z
	paramsX.append(0) # ChrMarine@Meander01 X
	paramsY.append(0) # ChrMarine@Meander01 Y
	paramsZ.append(0) # ChrMarine@Meander01 Z
	paramsX.append(0) # ChrMarine@Run01 X
	paramsY.append(0) # ChrMarine@Run01 Y
	paramsZ.append(0) # ChrMarine@Run01 Z
	paramsX.append(0) # ChrMarine@RunCircleLf01_smooth X
	paramsY.append(0) # ChrMarine@RunCircleLf01_smooth Y
	paramsZ.append(0) # ChrMarine@RunCircleLf01_smooth Z
	paramsX.append(0) # ChrMarine@RunCircleRt01_smooth X
	paramsY.append(0) # ChrMarine@RunCircleRt01_smooth Y
	paramsZ.append(0) # ChrMarine@RunCircleRt01_smooth Z
	paramsX.append(0) # ChrMarine@RunTightCircleLf01 X
	paramsY.append(0) # ChrMarine@RunTightCircleLf01 Y
	paramsZ.append(0) # ChrMarine@RunTightCircleLf01 Z
	paramsX.append(0) # ChrMarine@RunTightCircleRt01 X
	paramsY.append(0) # ChrMarine@RunTightCircleRt01 Y
	paramsZ.append(0) # ChrMarine@RunTightCircleRt01 Z
	paramsX.append(0) # ChrMarine@StrafeFastLf01_smooth X
	paramsY.append(0) # ChrMarine@StrafeFastLf01_smooth Y
	paramsZ.append(0) # ChrMarine@StrafeFastLf01_smooth Z
	paramsX.append(0) # ChrMarine@StrafeFastRt01_smooth X
	paramsY.append(0) # ChrMarine@StrafeFastRt01_smooth Y
	paramsZ.append(0) # ChrMarine@StrafeFastRt01_smooth Z
	paramsX.append(0) # ChrMarine@Walk01 X
	paramsY.append(0) # ChrMarine@Walk01 Y
	paramsZ.append(0) # ChrMarine@Walk01 Z
	paramsX.append(0) # ChrMarine@WalkCircleLf01_smooth X
	paramsY.append(0) # ChrMarine@WalkCircleLf01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkCircleLf01_smooth Z
	paramsX.append(0) # ChrMarine@WalkCircleRt01_smooth X
	paramsY.append(0) # ChrMarine@WalkCircleRt01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkCircleRt01_smooth Z
	paramsX.append(0) # ChrMarine@WalkTightCircleLf01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleLf01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleLf01_smooth Z
	paramsX.append(0) # ChrMarine@WalkTightCircleRt01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleRt01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleRt01_smooth Z
	paramsX.append(0) # ChrMarine@WalkTightCircleLf01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleLf01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleLf01_smooth Z
	paramsX.append(0) # ChrMarine@WalkTightCircleRt01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleRt01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleRt01_smooth Z

	paramsX.append(0) # ChrMarine@WalkTightCircleLf01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleLf01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleLf01_smooth Z
	paramsX.append(0) # ChrMarine@WalkTightCircleRt01_smooth X
	paramsY.append(0) # ChrMarine@WalkTightCircleRt01_smooth Y
	paramsZ.append(0) # ChrMarine@WalkTightCircleRt01_smooth Z

	for i in range(0, len(motions)):
		statemarineLocomotion.addMotion(motions[i], paramsX[i], paramsY[i], paramsZ[i])

	points0 = DoubleVec()
	points0.append(0) # ChrMarine@Idle01 0
	points0.append(0) # ChrMarine@Jog01 0
	points0.append(0.21) # ChrMarine@Meander01 0
	points0.append(0) # ChrMarine@Run01 0
	points0.append(0.12) # ChrMarine@RunCircleLf01_smooth 0
	points0.append(0.52) # ChrMarine@RunCircleRt01_smooth 0
	points0.append(0.51) # ChrMarine@RunTightCircleLf01 0
	points0.append(0.04) # ChrMarine@RunTightCircleRt01 0
	points0.append(0.90) # ChrMarine@StrafeSlowLf01 0
	points0.append(0.44) # ChrMarine@StrafeSlowRt01 0
	points0.append(0.22) # ChrMarine@Walk01 0
	points0.append(0.88) # ChrMarine@WalkCircleLf01_smooth 0
	points0.append(0.28) # ChrMarine@WalkCircleRt01_smooth 0
	points0.append(1.09) # ChrMarine@WalkTightCircleLf01_smooth 0
	points0.append(0.26) # ChrMarine@WalkTightCircleRt01_smooth 0
	points0.append(0) # ChrMarine@Turn360Lf01 0
	points0.append(0.70) # ChrMarine@Turn360Rt01 0
	points0.append(0.09) # ChrMarine@StrafeFastLf01_smooth 0
	points0.append(0.43) # ChrMarine@StrafeFastRt01_smooth 0

	statemarineLocomotion.addCorrespondencePoints(motions, points0)
	points1 = DoubleVec()
	points1.append(0.56) # ChrMarine@Idle01 1
	points1.append(0.42) # ChrMarine@Jog01 1
	points1.append(0.90) # ChrMarine@Meander01 1
	points1.append(0.30) # ChrMarine@Run01 1
	points1.append(0.52) # ChrMarine@RunCircleLf01_smooth 1
	points1.append(0.89) # ChrMarine@RunCircleRt01_smooth 1
	points1.append(0.86) # ChrMarine@RunTightCircleLf01 1
	points1.append(0.54) # ChrMarine@RunTightCircleRt01 1
	points1.append(1.53) # ChrMarine@StrafeSlowLf01 1
	points1.append(0.90) # ChrMarine@StrafeSlowRt01 1
	points1.append(0.72) # ChrMarine@Walk01 1
	points1.append(1.58) # ChrMarine@WalkCircleLf01_smooth 1
	points1.append(0.95) # ChrMarine@WalkCircleRt01_smooth 1
	points1.append(1.80) # ChrMarine@WalkTightCircleLf01_smooth 1
	points1.append(1.00) # ChrMarine@WalkTightCircleRt01_smooth 1
	points1.append(0.70) # ChrMarine@Idle01 1
	points1.append(1.25) # ChrMarine@Jog01 1
	points1.append(0.43) # ChrMarine@StrafeFastLf01_smooth 1
	points1.append(0.88) # ChrMarine@StrafeFastRt01_smooth 1

	statemarineLocomotion.addCorrespondencePoints(motions, points1)
	points2 = DoubleVec()
	points2.append(1.12) # ChrMarine@Idle01 2
	points2.append(0.75) # ChrMarine@Jog01 2
	points2.append(1.45) # ChrMarine@Meander01 2
	points2.append(0.57) # ChrMarine@Run01 2
	points2.append(0.89) # ChrMarine@RunCircleLf01_smooth 2
	points2.append(1.29) # ChrMarine@RunCircleRt01_smooth 2
	points2.append(1.15) # ChrMarine@RunTightCircleLf01 2
	points2.append(0.86) # ChrMarine@RunTightCircleRt01 2
	points2.append(2.15) # ChrMarine@StrafeSlowLf01 2
	points2.append(1.53) # ChrMarine@StrafeSlowRt01 2
	points2.append(1.22) # ChrMarine@Walk01 2
	points2.append(2.28) # ChrMarine@WalkCircleLf01_smooth 2
	points2.append(1.59) # ChrMarine@WalkCircleRt01_smooth 2
	points2.append(2.47) # ChrMarine@WalkTightCircleLf01_smooth 2
	points2.append(1.82) # ChrMarine@WalkTightCircleRt01_smooth 2
	points2.append(1.29) # ChrMarine@Idle01 2
	points2.append(1.75) # ChrMarine@Jog01 2
	points2.append(0.88) # ChrMarine@StrafeFastLf01_smooth 2
	points2.append(1.24) # ChrMarine@StrafeFastRt01_smooth 2



	statemarineLocomotion.addCorrespondencePoints(motions, points2)
	points3 = DoubleVec()
	points3.append(1.68) # ChrMarine@Idle01 3
	points3.append(1.07) # ChrMarine@Jog01 3
	points3.append(2.06) # ChrMarine@Meander01 3
	points3.append(0.85) # ChrMarine@Run01 3
	points3.append(1.29) # ChrMarine@RunCircleLf01_smooth 3
	points3.append(1.69) # ChrMarine@RunCircleRt01_smooth 3
	points3.append(1.51) # ChrMarine@RunTightCircleLf01 3
	points3.append(1.15) # ChrMarine@RunTightCircleRt01 3
	points3.append(2.74) # ChrMarine@StrafeSlowLf01 3
	points3.append(2.15) # ChrMarine@StrafeSlowRt01 3
	points3.append(1.74) # ChrMarine@Walk01 3
	points3.append(2.8) # ChrMarine@WalkCircleLf01_smooth 3
	points3.append(2.27) # ChrMarine@WalkCircleRt01_smooth 3
	points3.append(3.22) # ChrMarine@WalkTightCircleLf01_smooth 3
	points3.append(2.45) # ChrMarine@WalkTightCircleRt01_smooth 3
	points3.append(1.68) # ChrMarine@Idle01 3
	points3.append(2.15) # ChrMarine@Jog01 3
	points3.append(1.24) # ChrMarine@StrafeFastLf01_smooth 3
	points3.append(1.69) # ChrMarine@StrafeFastRt01_smooth 3

	statemarineLocomotion.addCorrespondencePoints(motions, points3)
	points4 = DoubleVec()
	points4.append(2.17) # ChrMarine@Idle01 4
	points4.append(1.40) # ChrMarine@Jog01 4
	points4.append(2.54) # ChrMarine@Meander01 4
	points4.append(1.07) # ChrMarine@Run01 4
	points4.append(1.69) # ChrMarine@RunCircleLf01_smooth 4
	points4.append(2.09) # ChrMarine@RunCircleRt01_smooth 4
	points4.append(1.91) # ChrMarine@RunTightCircleLf01 4
	points4.append(1.44) # ChrMarine@RunTightCircleRt01 4
	points4.append(3.17) # ChrMarine@StrafeFastLf01_smooth 4
	points4.append(2.74) # ChrMarine@StrafeFastRt01_smooth 4
	points4.append(2.29) # ChrMarine@Walk01 4
	points4.append(3.48) # ChrMarine@WalkCircleLf01_smooth 4
	points4.append(2.88) # ChrMarine@WalkCircleRt01_smooth 4
	points4.append(4.02) # ChrMarine@WalkTightCircleLf01_smooth 4
	points4.append(3.19) # ChrMarine@WalkTightCircleRt01_smooth 4
	points4.append(2.13) # ChrMarine@Idle01 4
	points4.append(2.83) # ChrMarine@Jog01 4
	points4.append(1.69) # ChrMarine@StrafeSlowLf01 4
	points4.append(2.03) # ChrMarine@StrafeSlowRt01 4

	statemarineLocomotion.addCorrespondencePoints(motions, points4)

	skeleton = scene.getSkeleton(skeletonName)
	joint = skeleton.getJointByName(baseJoint)
	travelDirection = ([0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0 ,0, 0, 0, -1, 1 ])

	for i in range(0, len(motions)):
		motion = scene.getMotion(motions[i])
		motion.connect(skeleton)
		correspondancePoints = statemarineLocomotion.getCorrespondancePoints(i)
		lenCorrespondancePoints = len(correspondancePoints)
		#speed = motion.getJointSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
		#omega = motion.getJointAngularSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
		speed = motion.getJointSpeed(joint, 0, motion.getDuration())
		#speedZ = motion.getJointSpeedAxis(joint, preFix+"Z", 0, motion.getDuration())
		if (travelDirection[i] != 0):
			direction = -motion.getJointSpeedAxis(joint, "X", 0, motion.getDuration())
		else:
			direction = travelDirection[i]
		
		omega = motion.getJointAngularSpeed(joint, 0, motion.getDuration())
		
		statemarineLocomotion.setParameter(motions[i], speed, omega, direction)
		#print "Motion " + motion.getName() + " (preFix+" + str(speed) + ", preFix+" + str(omega) + ", preFix+" + str(direction) + ")"
		motion.disconnect()		
	
	stanceArray = []
	stanceArray.append([0.2, 0.7, 1.25, 1.80]) # idle
	stanceArray.append([0.4, 0.05,1.1,0.75]) # jog
	stanceArray.append([0.75,0.2, 1.95, 1.45]) # meander
	stanceArray.append([0.3, 0.1, 0.85, 0.55]) # run
	stanceArray.append([0.4, 0.1, 1.25, 0.85]) # run circle lf
	stanceArray.append([0.1, 0.4, 0.85, 1.25]) # run circle rt
	stanceArray.append([0.1, 0.4, 0.74, 1.10]) # run tight circle lf
	stanceArray.append([0.4, 0.1, 1.10, 0.74]) # run tight circle rt
	stanceArray.append([0.1, 0.75, 1.3, 1.85]) # strafe slow lf
	stanceArray.append([0.75, 0.1, 1.85, 1.3]) # strafe slow rt
	stanceArray.append([0.65, 0.15, 1.80, 1.25]) # walk
	stanceArray.append([0.15, 0.85, 1.55, 2.20]) # walk circle lf
	stanceArray.append([0.85, 0.15, 2.20, 1.55]) # walk circle rt
	stanceArray.append([0.1, 1.0, 1.6, 2.45]) # walk tight circle lf
	stanceArray.append([1.0, 0.1, 2.45, 1.6]) # walk tight circle rt
	stanceArray.append([0.7, 0.1, 1.75, 1.20]) # turn 360 lf
	stanceArray.append([0.1, 0.7, 1.20, 1.75]) # turn 360 rt	
	stanceArray.append([0.45, 0.1, 1.20, 0.85]) # strafe fast lf
	stanceArray.append([0.1, 0.45, 0.85, 1.20]) # strafe fast rt
	
	for i in range(0, len(motions)):
		motionName = preFix + originalMotions[i]
		motion = scene.getMotion(motionName)
		motionDuration = motion.getDuration()		
		for j in range(0,2):
			s1 = stanceArray[i][0+j]
			s2 = stanceArray[i][2+j]
			leg = j
			statemarineLocomotion.addKeyTagValue(motionName,leg,"stance",s1);
			statemarineLocomotion.addKeyTagValue(motionName,leg,"stance",s2);	
			lift1 = (s1+0.15)%motionDuration
			lift2 = (s2+0.15)%motionDuration
			statemarineLocomotion.addKeyTagValue(motionName,leg,"lift",lift1);
			statemarineLocomotion.addKeyTagValue(motionName,leg,"lift",lift2);	
			land1 = (s2-0.15)%motionDuration
			land2 = (s1-0.15)%motionDuration
			statemarineLocomotion.addKeyTagValue(motionName,leg,"land",land1);
			statemarineLocomotion.addKeyTagValue(motionName,leg,"land",land2);	
			off1 = (lift1+0.1)%motionDuration
			off2 = (lift2+0.1)%motionDuration
			statemarineLocomotion.addKeyTagValue(motionName,leg,"lift-off",off1);
			statemarineLocomotion.addKeyTagValue(motionName,leg,"lift-off",off2);
			str1 = (land1-0.15)%motionDuration
			str2 = (land2-0.15)%motionDuration
			statemarineLocomotion.addKeyTagValue(motionName,leg,"strike",str1);
			statemarineLocomotion.addKeyTagValue(motionName,leg,"strike",str2);	
	
	statemarineLocomotion.buildMotionAnalysis(origSkelName,baseJoint,originalMotions, preFix);		
		
		
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")

	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")

	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")

	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeSlowLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")
	statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")

	
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Run01", preFix+"ChrMarine@Turn360Lf01")

# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleLf01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleLf01_smooth", preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkTightCircleLf01_smooth", preFix+"ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleLf01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Run01", preFix+"ChrMarine@Turn360Lf01")

# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastLf01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")

# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Meander01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01", preFix+"ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkCircleRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Jog01", preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Run01", preFix+"ChrMarine@RunCircleRt01_smooth", preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@Idle01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")
# statemarineLocomotion.addTetrahedron(preFix+"ChrMarine@RunTightCircleRt01", preFix+"ChrMarine@StrafeFastRt01_smooth", preFix+"ChrMarine@WalkTightCircleRt01_smooth", preFix+"ChrMarine@Turn360Rt01")

