# state marineLocomotion
# autogenerated by SmartBody

stateManager = scene.getStateManager()

#statemarineLocomotion = stateManager.createState3D("ChrMarineLocomotion")
statemarineLocomotion = stateManager.createState3D("backovicLocomotion")

motions = StringVec()
motions.append("ChrMarine@Idle01")
motions.append("ChrMarine@Jog01")
motions.append("ChrMarine@Meander01")
motions.append("ChrMarine@Run01")
motions.append("ChrMarine@RunCircleLf01")
motions.append("ChrMarine@RunCircleRt01")
motions.append("ChrMarine@RunTightCircleLf01")
motions.append("ChrMarine@RunTightCircleRt01")
motions.append("ChrMarine@StrafeFastLf01")
motions.append("ChrMarine@StrafeFastRt01")
motions.append("ChrMarine@Walk01")
motions.append("ChrMarine@WalkCircleLf01")
motions.append("ChrMarine@WalkCircleRt01")
motions.append("ChrMarine@WalkTightCircleLf01")
motions.append("ChrMarine@WalkTightCircleRt01")
motions.append("ChrMarine@Turn360Lf01")
motions.append("ChrMarine@Turn360Rt01")

paramsX = DoubleVec()
paramsY = DoubleVec()
paramsZ = DoubleVec()
paramsX.append(0) # ChrMarine@Idle01 X
paramsY.append(0) # ChrMarine@Idle01 Y
paramsZ.append(0) # ChrMarine@Idle01 Z
paramsX.append(0) # ChrMarine@Jog01 X
paramsY.append(0) # ChrMarine@Jog01 Y
paramsZ.append(0) # ChrMarine@Jog01 Z
paramsX.append(0) # ChrMarine@Meander01 X
paramsY.append(0) # ChrMarine@Meander01 Y
paramsZ.append(0) # ChrMarine@Meander01 Z
paramsX.append(0) # ChrMarine@Run01 X
paramsY.append(0) # ChrMarine@Run01 Y
paramsZ.append(0) # ChrMarine@Run01 Z
paramsX.append(0) # ChrMarine@RunCircleLf01 X
paramsY.append(0) # ChrMarine@RunCircleLf01 Y
paramsZ.append(0) # ChrMarine@RunCircleLf01 Z
paramsX.append(0) # ChrMarine@RunCircleRt01 X
paramsY.append(0) # ChrMarine@RunCircleRt01 Y
paramsZ.append(0) # ChrMarine@RunCircleRt01 Z
paramsX.append(0) # ChrMarine@RunTightCircleLf01 X
paramsY.append(0) # ChrMarine@RunTightCircleLf01 Y
paramsZ.append(0) # ChrMarine@RunTightCircleLf01 Z
paramsX.append(0) # ChrMarine@RunTightCircleRt01 X
paramsY.append(0) # ChrMarine@RunTightCircleRt01 Y
paramsZ.append(0) # ChrMarine@RunTightCircleRt01 Z
paramsX.append(0) # ChrMarine@StrafeFastLf01 X
paramsY.append(0) # ChrMarine@StrafeFastLf01 Y
paramsZ.append(0) # ChrMarine@StrafeFastLf01 Z
paramsX.append(0) # ChrMarine@StrafeFastRt01 X
paramsY.append(0) # ChrMarine@StrafeFastRt01 Y
paramsZ.append(0) # ChrMarine@StrafeFastRt01 Z
paramsX.append(0) # ChrMarine@Walk01 X
paramsY.append(0) # ChrMarine@Walk01 Y
paramsZ.append(0) # ChrMarine@Walk01 Z
paramsX.append(0) # ChrMarine@WalkCircleLf01 X
paramsY.append(0) # ChrMarine@WalkCircleLf01 Y
paramsZ.append(0) # ChrMarine@WalkCircleLf01 Z
paramsX.append(0) # ChrMarine@WalkCircleRt01 X
paramsY.append(0) # ChrMarine@WalkCircleRt01 Y
paramsZ.append(0) # ChrMarine@WalkCircleRt01 Z
paramsX.append(0) # ChrMarine@WalkTightCircleLf01 X
paramsY.append(0) # ChrMarine@WalkTightCircleLf01 Y
paramsZ.append(0) # ChrMarine@WalkTightCircleLf01 Z
paramsX.append(0) # ChrMarine@WalkTightCircleRt01 X
paramsY.append(0) # ChrMarine@WalkTightCircleRt01 Y
paramsZ.append(0) # ChrMarine@WalkTightCircleRt01 Z
paramsX.append(0) # ChrMarine@WalkTightCircleLf01 X
paramsY.append(0) # ChrMarine@WalkTightCircleLf01 Y
paramsZ.append(0) # ChrMarine@WalkTightCircleLf01 Z
paramsX.append(0) # ChrMarine@WalkTightCircleRt01 X
paramsY.append(0) # ChrMarine@WalkTightCircleRt01 Y
paramsZ.append(0) # ChrMarine@WalkTightCircleRt01 Z

for i in range(0, len(motions)):
	statemarineLocomotion.addMotion(motions[i], paramsX[i], paramsY[i], paramsZ[i])

points0 = DoubleVec()
points0.append(0) # ChrMarine@Idle01 0
points0.append(0) # ChrMarine@Jog01 0
points0.append(0.21) # ChrMarine@Meander01 0
points0.append(0) # ChrMarine@Run01 0
points0.append(0.65) # ChrMarine@RunCircleLf01 0
points0.append(0.18) # ChrMarine@RunCircleRt01 0
points0.append(0.51) # ChrMarine@RunTightCircleLf01 0
points0.append(0.04) # ChrMarine@RunTightCircleRt01 0
points0.append(0.90) # ChrMarine@StrafeFastLf01 0
points0.append(0.32) # ChrMarine@StrafeFastRt01 0
points0.append(0.22) # ChrMarine@Walk01 0
points0.append(0.88) # ChrMarine@WalkCircleLf01 0
points0.append(0.28) # ChrMarine@WalkCircleRt01 0
points0.append(1.09) # ChrMarine@WalkTightCircleLf01 0
points0.append(0.26) # ChrMarine@WalkTightCircleRt01 0
points0.append(0) # ChrMarine@Turn360Lf01 0
points0.append(0.70) # ChrMarine@Turn360Rt01 0

statemarineLocomotion.addCorrespondencePoints(motions, points0)
points1 = DoubleVec()
points1.append(0.56) # ChrMarine@Idle01 1
points1.append(0.42) # ChrMarine@Jog01 1
points1.append(0.90) # ChrMarine@Meander01 1
points1.append(0.30) # ChrMarine@Run01 1
points1.append(1.05) # ChrMarine@RunCircleLf01 1
points1.append(0.71) # ChrMarine@RunCircleRt01 1
points1.append(0.86) # ChrMarine@RunTightCircleLf01 1
points1.append(0.54) # ChrMarine@RunTightCircleRt01 1
points1.append(1.53) # ChrMarine@StrafeFastLf01 1
points1.append(0.95) # ChrMarine@StrafeFastRt01 1
points1.append(0.72) # ChrMarine@Walk01 1
points1.append(1.58) # ChrMarine@WalkCircleLf01 1
points1.append(0.95) # ChrMarine@WalkCircleRt01 1
points1.append(1.80) # ChrMarine@WalkTightCircleLf01 1
points1.append(1.00) # ChrMarine@WalkTightCircleRt01 1
points1.append(0.70) # ChrMarine@Idle01 1
points1.append(1.25) # ChrMarine@Jog01 1

statemarineLocomotion.addCorrespondencePoints(motions, points1)
points2 = DoubleVec()
points2.append(1.12) # ChrMarine@Idle01 2
points2.append(0.75) # ChrMarine@Jog01 2
points2.append(1.45) # ChrMarine@Meander01 2
points2.append(0.57) # ChrMarine@Run01 2
points2.append(1.46) # ChrMarine@RunCircleLf01 2
points2.append(1.08) # ChrMarine@RunCircleRt01 2
points2.append(1.15) # ChrMarine@RunTightCircleLf01 2
points2.append(0.86) # ChrMarine@RunTightCircleRt01 2
points2.append(2.15) # ChrMarine@StrafeFastLf01 2
points2.append(1.56) # ChrMarine@StrafeFastRt01 2
points2.append(1.22) # ChrMarine@Walk01 2
points2.append(2.28) # ChrMarine@WalkCircleLf01 2
points2.append(1.59) # ChrMarine@WalkCircleRt01 2
points2.append(2.47) # ChrMarine@WalkTightCircleLf01 2
points2.append(1.82) # ChrMarine@WalkTightCircleRt01 2
points2.append(1.29) # ChrMarine@Idle01 2
points2.append(1.75) # ChrMarine@Jog01 2


statemarineLocomotion.addCorrespondencePoints(motions, points2)
points3 = DoubleVec()
points3.append(1.68) # ChrMarine@Idle01 3
points3.append(1.07) # ChrMarine@Jog01 3
points3.append(2.06) # ChrMarine@Meander01 3
points3.append(0.85) # ChrMarine@Run01 3
points3.append(1.87) # ChrMarine@RunCircleLf01 3
points3.append(1.45) # ChrMarine@RunCircleRt01 3
points3.append(1.51) # ChrMarine@RunTightCircleLf01 3
points3.append(1.15) # ChrMarine@RunTightCircleRt01 3
points3.append(2.74) # ChrMarine@StrafeFastLf01 3
points3.append(2.07) # ChrMarine@StrafeFastRt01 3
points3.append(1.74) # ChrMarine@Walk01 3
points3.append(2.8) # ChrMarine@WalkCircleLf01 3
points3.append(2.27) # ChrMarine@WalkCircleRt01 3
points3.append(3.22) # ChrMarine@WalkTightCircleLf01 3
points3.append(2.45) # ChrMarine@WalkTightCircleRt01 3
points3.append(1.68) # ChrMarine@Idle01 3
points3.append(2.15) # ChrMarine@Jog01 3

statemarineLocomotion.addCorrespondencePoints(motions, points3)
points4 = DoubleVec()
points4.append(2.17) # ChrMarine@Idle01 4
points4.append(1.40) # ChrMarine@Jog01 4
points4.append(2.54) # ChrMarine@Meander01 4
points4.append(1.07) # ChrMarine@Run01 4
points4.append(2.35) # ChrMarine@RunCircleLf01 4
points4.append(1.88) # ChrMarine@RunCircleRt01 4
points4.append(1.91) # ChrMarine@RunTightCircleLf01 4
points4.append(1.44) # ChrMarine@RunTightCircleRt01 4
points4.append(3.17) # ChrMarine@StrafeFastLf01 4
points4.append(2.76) # ChrMarine@StrafeFastRt01 4
points4.append(2.29) # ChrMarine@Walk01 4
points4.append(3.48) # ChrMarine@WalkCircleLf01 4
points4.append(2.88) # ChrMarine@WalkCircleRt01 4
points4.append(4.02) # ChrMarine@WalkTightCircleLf01 4
points4.append(3.19) # ChrMarine@WalkTightCircleRt01 4
points4.append(2.13) # ChrMarine@Idle01 4
points4.append(2.83) # ChrMarine@Jog01 4

statemarineLocomotion.addCorrespondencePoints(motions, points4)

skeleton = scene.getSkeleton("ChrBackovic.sk")
joint = skeleton.getJointByName("base")
travelDirection = ([0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0 ,0, 0, 0 ])

for i in range(0, len(motions)):
	motion = scene.getMotion(motions[i])
	motion.connect(skeleton)
	correspondancePoints = statemarineLocomotion.getCorrespondancePoints(i)
	lenCorrespondancePoints = len(correspondancePoints)
	#speed = motion.getJointSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
	#omega = motion.getJointAngularSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
	speed = motion.getJointSpeed(joint, 0, correspondancePoints[lenCorrespondancePoints - 1] - correspondancePoints[0])
	omega = motion.getJointAngularSpeed(joint, 0, correspondancePoints[lenCorrespondancePoints - 1] - correspondancePoints[0])
	direction = travelDirection[i]
	statemarineLocomotion.setParameter(motions[i], speed, omega, direction)
	motion.disconnect()
	
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@Meander01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleLf01", "ChrMarine@WalkTightCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Meander01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleLf01", "ChrMarine@WalkTightCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunCircleLf01", "ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@RunCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@Run01", "ChrMarine@RunCircleLf01", "ChrMarine@StrafeFastLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Run01", "ChrMarine@RunCircleLf01", "ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkTightCircleLf01", "ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkTightCircleLf01", "ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastLf01", "ChrMarine@Run01", "ChrMarine@Turn360Lf01")

statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@Meander01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleLf01", "ChrMarine@WalkTightCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Meander01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01", "ChrMarine@WalkCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleLf01", "ChrMarine@WalkTightCircleLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunCircleLf01", "ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@RunCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@Run01", "ChrMarine@RunCircleLf01", "ChrMarine@StrafeFastRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Run01", "ChrMarine@RunCircleLf01", "ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkTightCircleLf01", "ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkTightCircleLf01", "ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleLf01", "ChrMarine@StrafeFastRt01", "ChrMarine@Run01", "ChrMarine@Turn360Lf01")

statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@Meander01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleRt01", "ChrMarine@WalkTightCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Meander01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkCircleRt01", "ChrMarine@WalkTightCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunCircleRt01", "ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@RunCircleRt01", "ChrMarine@StrafeFastLf01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@Run01", "ChrMarine@RunCircleRt01", "ChrMarine@StrafeFastLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Run01", "ChrMarine@RunCircleRt01", "ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastLf01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkTightCircleRt01", "ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastLf01", "ChrMarine@WalkTightCircleRt01", "ChrMarine@Turn360Rt01")

statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@Meander01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleRt01", "ChrMarine@WalkTightCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Meander01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01", "ChrMarine@WalkCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkCircleRt01", "ChrMarine@WalkTightCircleRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunCircleRt01", "ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@RunCircleRt01", "ChrMarine@StrafeFastRt01", "ChrMarine@Walk01")
statemarineLocomotion.addTetrahedron("ChrMarine@Jog01", "ChrMarine@Run01", "ChrMarine@RunCircleRt01", "ChrMarine@StrafeFastRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Run01", "ChrMarine@RunCircleRt01", "ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastRt01")
statemarineLocomotion.addTetrahedron("ChrMarine@Idle01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkTightCircleRt01", "ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrMarine@RunTightCircleRt01", "ChrMarine@StrafeFastRt01", "ChrMarine@WalkTightCircleRt01", "ChrMarine@Turn360Rt01")

