#!/bin/sh
SBMINPUT="-noninteractive -seqpath ../../../../test_suite/input/viseme_basic_test -seq viseme_basic_test.seq -facebone"
OPTION_1=IMG
THRESHOLD_1=3000
OPTION_2=IMG
THRESHOLD_2=3000
OPTION_3=IMG
THRESHOLD_3=3000
OPTION_4=IMG
THRESHOLD_4=3000
OPTION_5=IMG
THRESHOLD_5=3000
OPTION_6=IMG
THRESHOLD_6=3000
OPTION_7=IMG
THRESHOLD_7=3000
OPTION_8=IMG
THRESHOLD_8=3000
OPTION_9=IMG
THRESHOLD_9=3000
OPTION_10=IMG
THRESHOLD_10=3000
OPTION_11=IMG
THRESHOLD_11=3000
OPTION_12=IMG
THRESHOLD_12=3000
OPTION_13=IMG
THRESHOLD_13=3000
OPTION_14=IMG
THRESHOLD_14=3000
NUMOFCOMP=14

SBMBIN=$1
INPUTDIR=$2
OUTPUTDIR=$3
SBMEXE=$4
BASENAME=`basename $0 .sh`

cd $INPUTDIR
source ../src/common_test.sh

COUNTER=0
RESULT=""
FLAG="SUCCESS"
REDOFLAG="NOREDO"
while [ $COUNTER -lt $NUMOFCOMP ]; do
	let COUNTER=COUNTER+1
	OPTION=$(eval echo \$$"OPTION_$COUNTER")
	THRESHOLD=$(eval echo \$$"THRESHOLD_$COUNTER")
	cd $INPUTDIR
	RESULT=`source ../src/common_comp.sh $OPTION $COUNTER $THRESHOLD` 
	if [ $RESULT = "FAILURE" ]; then
		FLAG=FAILURE
	fi
	if [ $RESULT = "REDO" ]; then
		REDOFLAG=REDO
	fi

done

if [ $FLAG = "FAILURE" ]; then
	echo FAILURE
else
	echo SUCCESS
fi
if [ $REDOFLAG = "REDO" ]; then
	echo REDO
fi